services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9330:9000" # api
      - "9331:9001" # web ui
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio_data:/data
